In [1]:
import numpy as np

In [2]:
np.random.seed(1)

def relu(x):
    return (x > 0) * x  # returns x if x > 0
                        # return 0 otherwise
    
def relu2deriv(output):
    return output > 0   # returns 1 for input > 0
                        # return 0 otherwise

In [3]:
relu(-1000), relu(1000), relu2deriv(100), relu2deriv(-100)

(0, 1000, True, False)

In [4]:
alpha = 0.2
hidden_size = 4

In [5]:
streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

In [35]:
weights_0_1 = 2*np.random.random((3,hidden_size)) - 1    # 3x4
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1    # 4x1

In [7]:
for iteration in range(120):
    layer_2_error = 0
    for i in range(len(streetlights)):       
        layer_0 = streetlights[i:i+1]                                     
        layer_1 = relu(np.dot(layer_0,weights_0_1))                      
        layer_2 = np.dot(layer_1,weights_1_2)                             
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)      
        layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)                    
        layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)   
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)                
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)      
    if(iteration % 10 == 9):
        print("Error:" + str(layer_2_error))

Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05
Error:6.623830121108468e-07
Error:2.8900540237497683e-08
Error:1.2587641233552748e-09
Error:5.480552259746703e-11
Error:2.3860043209091744e-12
Error:1.0387504595876368e-13


In [84]:
i = 0

layer_0 = streetlights[i:i+1]  
layer_1 = relu(np.dot(layer_0,weights_0_1))  
layer_2 = np.dot(layer_1,weights_1_2)                              
layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)    
layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)               
layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)

var_list = ['layer_0', 'layer_1', 'layer_2', 'layer_2_error', 'layer_2_delta', 'layer_1_delta']
k=0
for i in [layer_0, layer_1, layer_2, layer_2_error, layer_2_delta, layer_1_delta]:
    
    print(var_list[k])
    k+=1
    print(i)
    print('-----------------')
    
print(layer_2_error)

layer_0
[[1 0 1]]
-----------------
layer_1
[[ 1.89350124  0.56266188 -0.          0.20958992]]
-----------------
layer_2
[[-1.64773354]]
-----------------
layer_2_error
42.61925911791417
-----------------
layer_2_delta
[[2.64773354]]
-----------------
layer_1_delta
[[-2.10110362 -0.27592812  0.         -1.09290948]]
-----------------
42.61925911791417
